### PR TITLE
Create a codespace for digital marketplace

### PR DESCRIPTION
**Pull request by kriscooke**
To check that the app runs on the codespace:
- connect to the codespace
- add environment variables (ask Brianna or Bryan)
- run `npm run back-end:watch` to start the back end
- follow the pop-up to see the application running on a forwarded port (or if you miss it, go to the ports tab and click 3000)
- run `npm run front-end:watch` for the front-end

### CODE REVIEW

**Comment by wenzowski** [comment]
I think it would be incredibly valuable to future teammates (and possibly those of us who use codespaces infrequently) to have those instructions committed as part of this pr in, say, a `docs/github_codespaces.yml`.

**Comment by BCerki** [comment]
> I think it would be incredibly valuable to future teammates (and possibly those of us who use codespaces infrequently) to have those instructions committed as part of this pr in, say, a `docs/github_codespaces.yml`.

This was awhile ago, so @BryanGK, please confirm/correct, but I believe this is the situation with PRs 1-3:
- This PR (1) just sets up the codespace, no docs
- PR-3 adds keycloak to the codespace and gives both general and keycloak-specific instructions in the readme (better to move the general instructions to a `docs` file in this PR, @wenzowski? Why a `.yml` vs `.md`?)
- PR-2 sets up codespaces locally in a docker container, but relies on some of the files from PR-3 to work correctly (that's why it's not going straight to `main`)

**Comment by wenzowski** [comment]
@BCerki typo, meant `docs/github_codespaces.md`!

**Comment by BCerki** [comment]
To-do:
- docs in docs folder
- rebase and pass CI
- update node to 16
- open in codespaces to check

**Review by BryanGK — APPROVED** [review]
This looks good!

**Pull request merged**
