### PR TITLE
Create pull_request_template.md

### LINKED ISSUE #19: Definition of Done
Since the pull request peer review process is centred around evaluating our teammates work against our development team definition of done, maybe we should draft this agreement as a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)?

### PR DESCRIPTION
**Pull request by BCerki**
This PR:
- creates a PR template as a starting point for the team's definition of done 
- creates issue templates as a starting point for team's definition of ready

### CODE REVIEW

**Comment by BryanGK** [comment]
Great start @BCerki I added some of the templates and configuration from the service-development-toolkit. Have a look and see if you like them. Also can I suggest we move the `pull_request_template` to either the `.github` or `docs` folder? I found this link on [templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) not sure if you'd seen it or not.

**Review by BryanGK — DISMISSED** [review]
This looks good to me, but feel free to nix my changes if you don't like them and I can re-review

**Comment by BCerki** [comment]
> Great start @BCerki I added some of the templates and configuration from the service-development-toolkit. Have a look and see if you like them. Also can I suggest we move the `pull_request_template` to either the `.github` or `docs` folder? I found this link on [templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) not sure if you'd seen it or not.

These look great

**Review by BryanGK — APPROVED** [review]
Let's GO!! 🚢

**Pull request merged**
