### PR TITLE
33 pre commit changes

### LINKED ISSUE #33: Run pre-commit on codebase
Run pre-commit on all files so that these changes can be in a separate PR from the changes that set up pre-commit ci

### PR DESCRIPTION
**Pull request by BCerki**
This PR:
- contains one manual change to the `.pre-commit-config.yaml`
- updates the secrets file (automatically done by pre-commit)
- cleans up repo files using pre-commit (automatically done by pre-commit)

The pre-commit CI is failing because it requires some additional configuration. This is addressed in https://github.com/button-inc/digital_marketplace/pull/29. If preferred, I can turn off this action temporarily.

### CODE REVIEW

**Comment by wenzowski** [comment]
@BCerki I think you mentioned on chat that you'll fix pre-commit.ci as part of this PR, yes? https://github.com/button-inc/digital_marketplace/pull/13#discussion_r761509752

**Comment by BCerki** [comment]
> @BCerki I think you mentioned on chat that you'll fix pre-commit.ci as part of this PR, yes? [#13 (comment)](https://github.com/button-inc/digital_marketplace/pull/13#discussion_r761509752)

I'm fixing the ssh known hosts error and other pre-commit ci errors as part of https://github.com/button-inc/digital_marketplace/pull/29. This one is just about getting the files in shape so pre-commit ci doesn't make a bunch of auto-commits that clutter up 29.

**Comment by wenzowski** [comment]
Perfect, thanks! That helps with the review :)

**Review by wenzowski — DISMISSED** [review]
:shipit:

**Comment by wenzowski** [comment]
I'd merge #32 first, if possible. There might be conflict in `.eslintrc.js` as both PRs touch L24. But maybe we'll git lucky ;)

**Comment by BCerki** [comment]
@wenzowski, I did get a merge conflict on this. I resolved it in the online editor, but it looks like that killed your approving review

**Comment by wenzowski** [comment]
For other reviewers, this is easier to make sense of using `git diff -w` to ignore insignificant whitespace changes than using the github gui.

**Review by wenzowski — APPROVED** [review]

**Pull request merged**
