### PR TITLE
Pin npm package versions

### LINKED ISSUE #61: Pin package versions
As a developer I want to pin package versions in the `package.json` file, so that we have fewer changes to the `package-lock.json` and in the future migrate from `npm` to `yarn`

DoD:
- all package versions pinned to a working version

ref #6

### PR DESCRIPTION
**Pull request by BryanGK**
This PR pins packages to their resolved versions. Any minor version bumps were resolved versions.

ref #61

### CODE REVIEW

**Review by mikevespi — DISMISSED** [review]
Nice, this should help the switch to yarn in the future too! 🚢

**Review by wenzowski — CHANGES_REQUESTED** [review]
Let's hold on merge of this until we make a team agreement to migrate to `yarn` (or not, as the case may be).

**Comment by wenzowski** [comment]
From our convo on teams, [yarn can import `package-lock.json` state](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/), which would be a better migration path.

**Comment by wenzowski** [comment]
via backchannel:

> [5:33 p.m.] Matthieu Foucault
    You might, however, want to use tildes ~ instead of carets ^

https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json

**Comment by BCerki** [comment]
Migrated to yarn using `yarn import` in #122, so this work no longer required

**Pull request closed without merging**
